### ISSUE TITLE
trace_flags

### ISSUE THREAD

**Issue by GLoOoccK** [SmileYzn/AccuracyFix#29]
@SmileYzn

Add FTRACE_BULLET to return compatibility with plugins that use this code:

https://github.com/s1lentq/ReGameDLL_CS/pull/813

in:

https://github.com/SmileYzn/AccuracyFix/blob/main/AccuracyFix/AccuracyFix.cpp#L101

```cpp
gpGlobals->trace_flags = FTRACE_BULLET;
g_engfuncs.pfnTraceLine(vStart, vEndRes, fNoMonsters, pentToSkip, ptr);
```

I don't know if the same code could be added here as well:

https://github.com/SmileYzn/AccuracyFix/blob/main/AccuracyFix/AccuracyUtil.cpp#L94

```cpp
gpGlobals->trace_flags = FTRACE_BULLET;
g_engfuncs.pfnTraceLine(v_src, v_dest, 0, pEntity, &Result);
```

**Comment by SmileYzn** [comment]
Added, thanks for tip

Ps. This cam be a fix for flash bug in ReGameDLL_CS:

https://github.com/s1lentq/ReGameDLL_CS/issues/854

??

**Comment by GLoOoccK** [comment]
It worked, but it causes problems when using:

https://github.com/alliedmodders/amxmodx/blob/master/plugins/cstrike/statsx.sma#L172

```cpp
register_event("StatusValue", "eventShowRank", "bd", "1=2")
```

So it would just be this part:

https://github.com/SmileYzn/AccuracyFix/blob/main/AccuracyFix/AccuracyFix.cpp#L101

I'll find out about this flashbang problem

**Comment by GLoOoccK** [comment]
@SmileYzn

It worked, but it causes problems when using:

https://github.com/alliedmodders/amxmodx/blob/master/plugins/cstrike/statsx.sma#L172

```cpp
register_event("StatusValue", "eventShowRank", "bd", "1=2")
```

Sometimes he ignores his teammate and directly shows his opponent's name, but now when he shoots a teammate he deals damage with all weapons

I'll find out about this flashbang problem

**Comment by SmileYzn** [comment]
To fix friendly aim that maybe need to reset trace_flags to default after trace line?

**Comment by GLoOoccK** [comment]
I tried resetting it to 0 and it didn't work

**Comment by GLoOoccK** [comment]
@SmileYzn

I tested this and it worked:

```cpp
if (gpGlobals->trace_flags & FTRACE_BULLET)
{
	gpGlobals->trace_flags = FTRACE_BULLET;
	g_engfuncs.pfnTraceLine(vStart, vEndRes, fNoMonsters, pentToSkip, ptr);
}
```

Didn't work:

```cpp
if (gpGlobals->trace_flags & FTRACE_BULLET)
{
	gpGlobals->trace_flags = FTRACE_BULLET;
}

g_engfuncs.pfnTraceLine(vStart, vEndRes, fNoMonsters, pentToSkip, ptr);
```

Because ReGameDLL will set gpGlobals->trace_flags = FTRACE_BULLET automatically before calling the hook:

https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/cbase.cpp#L1063
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/cbase.cpp#L1209
https://github.com/s1lentq/ReGameDLL_CS/blob/master/regamedll/dlls/cbase.cpp#L1369

We need to make sure we are only changing the code when we perform a shot, we need to set gpGlobals->trace_flags = FTRACE_BULLET again and this may solve the flashbang problem if the problem comes from the module

This part is not executed, so it can be removed gpGlobals->trace_flags = FTRACE_BULLET in:

https://github.com/SmileYzn/AccuracyFix/blob/main/AccuracyFix/AccuracyUtil.cpp#L94-L96

**Comment by SmileYzn** [comment]
So you tell to trace line fix only when trace_flags = FTRACE_BULLET?

´´´
if (gpGlobals->trace_flags & FTRACE_BULLET)
´´´

?

**Comment by GLoOoccK** [comment]
@SmileYzn

Yes, I needed this check and everything worked correctly again, it would look like this:

```cpp
if (gpGlobals->trace_flags & FTRACE_BULLET)
{
	gpGlobals->trace_flags = FTRACE_BULLET;
	g_engfuncs.pfnTraceLine(vStart, vEndRes, fNoMonsters, pentToSkip, ptr);
}
```

in:

https://github.com/SmileYzn/AccuracyFix/blob/main/AccuracyFix/AccuracyFix.cpp#L101-L103

**Comment by SmileYzn** [comment]
To be honest that if is needed to be in very first of of function

**Comment by SmileYzn** [comment]
Build is here: https://github.com/SmileYzn/AccuracyFix/actions/runs/10530588403

**Comment by GLoOoccK** [comment]
@SmileYzn

I just tested it and everything works perfectly now, thank you very much

**Comment by SmileYzn** [comment]
:pray:

**Comment by Escap3d** [comment]
@SmileYzn I installed a new action build plugin, but the shooting has become very unfair. Both bullets and spray are not working properly. Please fix it.

**Comment by SmileYzn** [comment]
The test fix is here:

https://github.com/SmileYzn/AccuracyFix/actions/runs/10551207451

FTRACE_BULLET is not a bitwise!

**Comment by SmileYzn** [comment]
So do not need to sign value to trace_flags?
Just check it on if at start of function?

**Comment by SmileYzn** [comment]
On my testsit fixed in all times, not only when shooting.

**Comment by Escap3d** [comment]
The long-range shooting with the pistol and assault rifle is still experiencing quite a few misses...

**Comment by SmileYzn** [comment]
I have removed that TRACE_BULLET check, it is only now for TRACE_FLASH

**Comment by Escap3d** [comment]
> I have removed that TRACE_BULLET check, it is only now for TRACE_FLASH

thanks bro its fix and shotting love it :D
